# Generated by Django 5.0.14 on 2026-09-05 03:16

import apps.environments.fields
import apps.environments.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('dev', '开发环境'), ('test', '测试环境'), ('staging', '预发布环境'), ('prod', '生产环境')], max_length=50, verbose_name='环境类型')),
                ('base_url', models.URLField(max_length=500, validators=[apps.environments.models.validate_environment_url], verbose_name='接口基础地址')),
                ('description', models.TextField(blank=True, verbose_name='环境说明')),
                ('status', models.CharField(choices=[('available', '可用'), ('maintenance', '维护中'), ('unavailable', '不可用')], default='unavailable', max_length=20, verbose_name='环境状态')),
                ('health_check_url', models.URLField(blank=True, max_length=500, validators=[apps.environments.models.validate_environment_url], verbose_name='健康检查地址')),
                ('health_status', models.CharField(choices=[('unknown', '未检查'), ('healthy', '健康'), ('unhealthy', '异常')], default='unknown', max_length=20, verbose_name='健康状态')),
                ('database_config', apps.environments.fields.EncryptedObjectField(blank=True, default=dict, verbose_name='数据库连接配置')),
                ('auth_config', apps.environments.fields.EncryptedObjectField(blank=True, default=dict, verbose_name='认证配置')),
                ('variables', apps.environments.fields.EncryptedObjectField(blank=True, default=dict, verbose_name='环境变量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '测试环境',
                'verbose_name_plural': '测试环境',
                'ordering': ('project__name', 'name'),
                'indexes': [models.Index(fields=['project', 'status'], name='env_project_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='environment',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='env_project_name_uniq'),
        ),
    ]
