# Generated by Django 5.0.14 on 2026-09-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='health_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近检查时间'),
        ),
        migrations.AddField(
            model_name='environment',
            name='health_latency_ms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='检查耗时'),
        ),
        migrations.AddField(
            model_name='environment',
            name='health_message',
            field=models.CharField(blank=True, max_length=200, verbose_name='检查结果'),
        ),
    ]
