# Generated by Django 5.0.14 on 2026-09-03 04:47

import apps.users.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('test_leader', '测试负责人'), ('tester', '测试工程师'), ('developer', '开发工程师'), ('viewer', '访客')], db_index=True, default='viewer', max_length=20, verbose_name='角色')),
                ('preferences', models.JSONField(blank=True, default=dict, validators=[apps.users.models.validate_json_object], verbose_name='偏好设置')),
                ('notification_preferences', models.JSONField(blank=True, default=dict, validators=[apps.users.models.validate_json_object], verbose_name='通知偏好')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
                'ordering': ('user__username',),
            },
        ),
    ]
