# Generated by Django 5.2.6 on 2026-09-09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Add one-time account activation and password reset tokens."""

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountActionToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("invitation", "账号激活"), ("password_reset", "密码重置")], max_length=30, verbose_name="动作类型")),
                ("token_hash", models.CharField(max_length=64, unique=True, verbose_name="令牌摘要")),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                ("used_at", models.DateTimeField(blank=True, null=True, verbose_name="使用时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="issued_account_action_tokens", to=settings.AUTH_USER_MODEL, verbose_name="发起人")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="account_action_tokens", to=settings.AUTH_USER_MODEL, verbose_name="目标用户")),
            ],
            options={
                "verbose_name": "账号动作令牌",
                "verbose_name_plural": "账号动作令牌",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="accountactiontoken",
            index=models.Index(fields=["user", "kind", "used_at"], name="users_action_user_kind_idx"),
        ),
        migrations.AddIndex(
            model_name="accountactiontoken",
            index=models.Index(fields=["expires_at"], name="users_action_expiry_idx"),
        ),
    ]
