# Generated by Django 5.2.6 on 2026-09-09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Add immutable account lifecycle audit evidence."""

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0002_accountactiontoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountAuditEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_username", models.CharField(max_length=150, verbose_name="目标账号快照")),
                ("event", models.CharField(choices=[("invited", "邀请账号"), ("invitation_resent", "重发邀请"), ("invitation_revoked", "撤销邀请"), ("activated", "激活账号"), ("password_reset_issued", "生成密码重置链接"), ("password_reset", "完成密码重置"), ("account_updated", "更新账号权限")], db_index=True, max_length=40, verbose_name="事件")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="安全元数据")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="发生时间")),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="account_audit_events", to=settings.AUTH_USER_MODEL, verbose_name="操作人")),
                ("target", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="target_account_audit_events", to=settings.AUTH_USER_MODEL, verbose_name="目标账号")),
            ],
            options={
                "verbose_name": "账号审计事件",
                "verbose_name_plural": "账号审计事件",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="accountauditevent",
            index=models.Index(fields=["target_username", "created_at"], name="users_audit_target_idx"),
        ),
        migrations.AddIndex(
            model_name="accountauditevent",
            index=models.Index(fields=["event", "created_at"], name="users_audit_event_idx"),
        ),
    ]
