# Generated by Django 5.2.6 on 2026-09-14

from django.db import migrations, models


def create_bootstrap_lock(apps, schema_editor) -> None:
    """Create the singleton row used to serialize first-run setup."""
    del schema_editor
    state_model = apps.get_model("users", "PlatformBootstrapState")
    state_model.objects.get_or_create(singleton_key=1)


class Migration(migrations.Migration):
    """Add the first-run bootstrap lock without changing existing accounts."""

    dependencies = [
        ("users", "0003_accountauditevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformBootstrapState",
            fields=[
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(
                        default=1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Platform bootstrap state",
                "verbose_name_plural": "Platform bootstrap state",
            },
        ),
        migrations.RunPython(create_bootstrap_lock, migrations.RunPython.noop),
    ]
