# Generated by Django 5.0.14 on 2026-09-04 08:04

import apps.agents.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configs', '0004_seed_default_prompts'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='智能体名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('agent_type', models.CharField(choices=[('general', '通用智能体'), ('requirement_analyst', '需求分析'), ('case_generator', '用例生成'), ('test_executor', '测试执行'), ('reviewer', '审核评估')], db_index=True, default='general', max_length=30, verbose_name='智能体类型')),
                ('knowledge_base_ids', models.JSONField(blank=True, default=list, validators=[apps.agents.models.validate_reference_list], verbose_name='知识库引用')),
                ('skill_ids', models.JSONField(blank=True, default=list, validators=[apps.agents.models.validate_reference_list], verbose_name='技能引用')),
                ('parameters', models.JSONField(blank=True, default=dict, validators=[apps.agents.models.validate_object], verbose_name='运行参数')),
                ('version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='版本')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('disabled', '停用')], db_index=True, default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_agents', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('model_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='configs.modelconfig', verbose_name='模型配置')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='projects.project', verbose_name='项目')),
                ('prompt_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='configs.promptconfig', verbose_name='提示词配置')),
            ],
            options={
                'verbose_name': '智能体',
                'verbose_name_plural': '智能体',
                'ordering': ('project__name', 'name', '-version'),
                'indexes': [models.Index(fields=['project', 'status', 'agent_type'], name='agents_project_status_type_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(fields=('project', 'name', 'version'), name='agents_project_name_version_uniq'),
        ),
    ]
