# Generated by Django 5.0.14 on 2026-09-14 01:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=100, verbose_name='Agent name snapshot')),
                ('agent_version', models.PositiveIntegerField(default=1, verbose_name='Agent version snapshot')),
                ('input_text', models.TextField(max_length=20000, verbose_name='Input')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, verbose_name='Execution status')),
                ('phase', models.CharField(blank=True, default='', max_length=40, verbose_name='Execution phase')),
                ('interrupt_signal', models.CharField(blank=True, choices=[('', ''), ('pause', 'pause'), ('cancel', 'cancel')], default='', max_length=20, verbose_name='Interrupt signal')),
                ('model_route', models.JSONField(blank=True, default=dict, verbose_name='Model route')),
                ('trace', models.JSONField(blank=True, default=list, verbose_name='Audit trace')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='Execution result')),
                ('error_code', models.CharField(blank=True, default='', max_length=80, verbose_name='Error code')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Error message')),
                ('retryable', models.BooleanField(default=False, verbose_name='Retryable')),
                ('task_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Task ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='agents.agent', verbose_name='Agent configuration')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_executions', to='projects.project', verbose_name='Project')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_executions', to=settings.AUTH_USER_MODEL, verbose_name='Requested by')),
            ],
            options={
                'verbose_name': 'Agent execution',
                'verbose_name_plural': 'Agent executions',
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['project', 'status', 'created_at'], name='agents_exec_project_status_idx'), models.Index(fields=['agent', 'created_at'], name='agents_exec_agent_time_idx')],
            },
        ),
    ]
