# Generated by Django 5.0.14 on 2026-09-06 07:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('requirement_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseGenerationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rounds', models.PositiveSmallIntegerField(default=0)),
                ('total_cases', models.PositiveIntegerField(default=0)),
                ('auto_cases', models.PositiveIntegerField(default=0)),
                ('manual_cases', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('generating', '生成中'), ('reviewing', '评审中'), ('completed', '已完成'), ('failed', '失败')], db_index=True, default='generating', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_generation_records', to='requirement_analysis.requirementdocument')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_generation_records', to='projects.project')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['project', 'status'], name='case_gen_project_status_idx')],
            },
        ),
    ]
