# Generated by Django 5.0.14 on 2026-09-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_generation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casegenerationrecord',
            name='cases',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='casegenerationrecord',
            name='coverage_report',
            field=models.JSONField(default=dict),
        ),
    ]
