# Generated by Django 5.0.14 on 2026-09-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_generation', '0002_casegenerationrecord_cases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casegenerationrecord',
            name='review_report',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='casegenerationrecord',
            name='review_rounds',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
