import request from './request'

export const listSkills = (params = {}) => request.get('/api/skills/', { params })
export const createSkill = (payload) => request.post('/api/skills/', payload)
export const updateSkill = (id, payload) => request.patch(`/api/skills/${id}/`, payload)
export const deleteSkill = (id) => request.delete(`/api/skills/${id}/`)
export const toggleSkill = (id) => request.post(`/api/skills/${id}/toggle/`)
export const executeSkill = (id, input) => request.post(`/api/skills/${id}/execute/`, { input })
export const listPermissionAudits = (params = {}) => request.get('/api/skills/permission-audits/', { params })
export const listInstallations = (params = {}) => request.get('/api/skills/installations/', { params })
export const createInstallation = (payload) => request.post('/api/skills/installations/', payload)
export const verifyInstallation = (id, payload) => request.post(`/api/skills/installations/${id}/verify/`, payload)
export const approveInstallation = (id) => request.post(`/api/skills/installations/${id}/approve/`)
export const installSkillInstallation = (id) => request.post(`/api/skills/installations/${id}/install/`)
export const rollbackInstallation = (id) => request.post(`/api/skills/installations/${id}/rollback/`)
export const uninstallInstallation = (id) => request.post(`/api/skills/installations/${id}/uninstall/`)
export const invokeInstallation = (id, permission, input = {}) => request.post(`/api/skills/installations/${id}/invoke/`, { permission, input })
