import request from './request'

export const listSkills = (params = {}) => request.get('/api/skills/', { params })
export const createSkill = (payload) => request.post('/api/skills/', payload)
export const updateSkill = (id, payload) => request.patch(`/api/skills/${id}/`, payload)
export const deleteSkill = (id) => request.delete(`/api/skills/${id}/`)
export const toggleSkill = (id) => request.post(`/api/skills/${id}/toggle/`)
export const executeSkill = (id, input) => request.post(`/api/skills/${id}/execute/`, { input })
export const listPermissionAudits = (params = {}) => request.get('/api/skills/permission-audits/', { params })
export const listInstallations = (params = {}) => request.get('/api/skills/installations/', { params })
export const createInstallation = (payload) => request.post('/api/skills/installations/', payload)
export const verifyInstallation = (id, payload) => request.post(`/api/skills/installations/${id}/verify/`, payload)
export const approveInstallation = (id) => request.post(`/api/skills/installations/${id}/approve/`)
export const installSkillInstallation = (id) => request.post(`/api/skills/installations/${id}/install/`)
export const rollbackInstallation = (id) => request.post(`/api/skills/installations/${id}/rollback/`)
export const uninstallInstallation = (id) => request.post(`/api/skills/installations/${id}/uninstall/`)
export const invokeInstallation = (id, permission, input = {}) => request.post(`/api/skills/installations/${id}/invoke/`, { permission, input })
export const listSkillChains = (params = {}) => request.get('/api/skill-chains/', { params })
export const createSkillChain = (payload) => request.post('/api/skill-chains/', payload)
export const updateSkillChain = (id, payload) => request.patch(`/api/skill-chains/${id}/`, payload)
export const deleteSkillChain = (id) => request.delete(`/api/skill-chains/${id}/`)
export const listSkillChainConfigurations = (params = {}) => request.get('/api/skill-chain-configurations/', { params })
export const createSkillChainConfiguration = (payload) => request.post('/api/skill-chain-configurations/', payload)
export const updateSkillChainConfiguration = (id, payload) => request.patch(`/api/skill-chain-configurations/${id}/`, payload)
export const deleteSkillChainConfiguration = (id) => request.delete(`/api/skill-chain-configurations/${id}/`)
export const resolveSkillChainConfiguration = (payload) => request.post('/api/skill-chain-configurations/resolve/', payload)
export const rollbackSkillChainConfiguration = (id) => request.post('/api/skill-chain-configurations/' + id + '/rollback/')
export const getSkillChainConfigurationHistory = (id) => request.get('/api/skill-chain-configurations/' + id + '/history/')
export const enableSkillChain = (id) => request.post('/api/skill-chains/' + id + '/enable/')
export const disableSkillChain = (id) => request.post('/api/skill-chains/' + id + '/disable/')
export const listSkillChainVersions = (id) => request.get('/api/skill-chains/' + id + '/versions/')
export const getSkillChainDiff = (id, compareTo) => request.get('/api/skill-chains/' + id + '/diff/', { params: { compare_to: compareTo } })
export const forkSkillChainDraft = (id) => request.post('/api/skill-chains/' + id + '/fork/')
export const verifySkillChain = (id) => request.post('/api/skill-chains/' + id + '/verify/')
export const publishSkillChain = (id) => request.post('/api/skill-chains/' + id + '/publish/')
export const pauseSkillChain = (id) => request.post('/api/skill-chains/' + id + '/pause/')
export const archiveSkillChain = (id) => request.post('/api/skill-chains/' + id + '/archive/')
export const rollbackSkillChainVersion = (id, targetVersionId) => request.post('/api/skill-chains/' + id + '/rollback/', { target_version_id: targetVersionId })
export const getSkillChainHistory = (id) => request.get('/api/skill-chains/' + id + '/history/')
export const listSkillChainRuns = (params = {}) => request.get('/api/skill-chain-runs/', { params })
export const startSkillChainRun = (payload) => request.post('/api/skill-chain-runs/', payload)
export const getSkillChainRun = (id) => request.get('/api/skill-chain-runs/' + id + '/')
export const getSkillChainRunEvents = (id) => request.get('/api/skill-chain-runs/' + id + '/events/')
export const pauseSkillChainRun = (id) => request.post('/api/skill-chain-runs/' + id + '/pause/')
export const resumeSkillChainRun = (id, input = {}) => request.post('/api/skill-chain-runs/' + id + '/resume/', { input })
export const cancelSkillChainRun = (id) => request.post('/api/skill-chain-runs/' + id + '/cancel/')
export const retrySkillChainRunNode = (id, node_id) => request.post('/api/skill-chain-runs/' + id + '/retry-node/', { node_id })
