# Generated by Django 5.0.14 on 2026-09-05 09:42

import apps.knowledge.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='知识库名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('category', models.CharField(choices=[('builtin', '内置知识'), ('project', '项目知识'), ('experience', '经验知识'), ('subject', '被测对象知识'), ('realtime', '实时知识'), ('personal', '个人知识')], db_index=True, default='project', max_length=20, verbose_name='知识分类')),
                ('status', models.CharField(choices=[('active', '启用'), ('archived', '归档')], db_index=True, default='active', max_length=20, verbose_name='状态')),
                ('metadata', models.JSONField(blank=True, default=dict, validators=[apps.knowledge.models.validate_object], verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_knowledge_bases', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_bases', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '知识库',
                'verbose_name_plural': '知识库',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('source_type', models.CharField(choices=[('file', '文件'), ('online_link', '在线链接'), ('manual', '手动录入'), ('api', 'API同步')], default='manual', max_length=20, verbose_name='来源类型')),
                ('source_url', models.URLField(blank=True, max_length=1000, verbose_name='来源地址')),
                ('file_path', models.CharField(blank=True, max_length=1000, verbose_name='文件路径')),
                ('content_text', models.TextField(blank=True, verbose_name='正文')),
                ('status', models.CharField(choices=[('uploaded', '已上传'), ('parsing', '解析中'), ('ready', '已解析'), ('failed', '解析失败')], db_index=True, default='uploaded', max_length=20, verbose_name='解析状态')),
                ('metadata', models.JSONField(blank=True, default=dict, validators=[apps.knowledge.models.validate_object], verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_knowledge_documents', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='knowledge.knowledgebase', verbose_name='知识库')),
            ],
            options={
                'verbose_name': '知识文档',
                'verbose_name_plural': '知识文档',
                'ordering': ('knowledge_base__name', 'title'),
            },
        ),
        migrations.CreateModel(
            name='QAPair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(verbose_name='问题')),
                ('answer', models.TextField(verbose_name='答案')),
                ('review_status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('paused', '已暂缓')], db_index=True, default='pending', max_length=20, verbose_name='审核状态')),
                ('quality_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='质量评分')),
                ('metadata', models.JSONField(blank=True, default=dict, validators=[apps.knowledge.models.validate_object], verbose_name='元数据')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_knowledge_qa_pairs', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_pairs', to='knowledge.knowledgebase', verbose_name='知识库')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_knowledge_qa_pairs', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_pairs', to='knowledge.document', verbose_name='来源文档')),
            ],
            options={
                'verbose_name': '知识问答对',
                'verbose_name_plural': '知识问答对',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField(default=0, verbose_name='分块序号')),
                ('content', models.TextField(verbose_name='分块内容')),
                ('vector', models.JSONField(blank=True, null=True, validators=[apps.knowledge.models.validate_vector], verbose_name='向量')),
                ('model_name', models.CharField(blank=True, max_length=150, verbose_name='向量模型')),
                ('metadata', models.JSONField(blank=True, default=dict, validators=[apps.knowledge.models.validate_object], verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='knowledge.document', verbose_name='文档')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='knowledge.knowledgebase', verbose_name='知识库')),
                ('qa_pair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='knowledge.qapair', verbose_name='问答对')),
            ],
            options={
                'verbose_name': '知识向量',
                'verbose_name_plural': '知识向量',
                'ordering': ('knowledge_base__name', 'chunk_index'),
            },
        ),
        migrations.AddIndex(
            model_name='knowledgebase',
            index=models.Index(fields=['project', 'category', 'status'], name='knowledge_scope_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebase',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='knowledge_project_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(check=models.Q(('source_url', ''), ('file_path', ''), ('content_text', ''), _negated=True), name='knowledge_document_source_present'),
        ),
        migrations.AddConstraint(
            model_name='embedding',
            constraint=models.UniqueConstraint(fields=('knowledge_base', 'document', 'chunk_index'), name='knowledge_document_chunk_uniq'),
        ),
    ]
