# Generated by Django 5.0.14 on 2026-09-05 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='review_note',
            field=models.CharField(blank=True, max_length=500, verbose_name='审核备注'),
        ),
        migrations.AddField(
            model_name='document',
            name='review_status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('paused', '已暂缓')], db_index=True, default='pending', max_length=20, verbose_name='审核状态'),
        ),
        migrations.AddField(
            model_name='document',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='document',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_knowledge_documents', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
    ]
