# Generated by Django 5.0.14 on 2026-09-05 15:02

import apps.skills.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='技能名称')),
                ('version', models.CharField(default='1.0.0', max_length=30, verbose_name='版本')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('category', models.CharField(choices=[('core', '核心'), ('specialized', '专业'), ('auxiliary', '辅助'), ('custom', '自定义')], db_index=True, default='core', max_length=20, verbose_name='分类')),
                ('triggers', models.JSONField(default=dict, validators=[apps.skills.models.validate_object], verbose_name='触发条件')),
                ('capabilities', models.JSONField(default=list, validators=[apps.skills.models.validate_string_list], verbose_name='能力列表')),
                ('tools', models.JSONField(default=list, validators=[apps.skills.models.validate_string_list], verbose_name='所需工具')),
                ('knowledge', models.JSONField(default=list, validators=[apps.skills.models.validate_string_list], verbose_name='所需知识')),
                ('input_schema', models.JSONField(default=dict, validators=[apps.skills.models.validate_object], verbose_name='输入定义')),
                ('output_schema', models.JSONField(default=dict, validators=[apps.skills.models.validate_object], verbose_name='输出定义')),
                ('status', models.CharField(choices=[('enabled', '启用'), ('disabled', '停用')], db_index=True, default='enabled', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_skills', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '技能',
                'verbose_name_plural': '技能',
                'ordering': ('name', 'version'),
            },
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('project', 'name', 'version'), name='skills_scope_name_version_uniq'),
        ),
    ]
