# Generated by Django 5.0.14 on 2026-09-20 02:10

import apps.skills.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('skills', '0008_seed_case_review_skill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillChain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='链名称')),
                ('version', models.CharField(default='1.0.0', max_length=30, verbose_name='链版本')),
                ('description', models.TextField(blank=True, verbose_name='链说明')),
                ('schema_version', models.CharField(default='skill-chain-v1', max_length=40, verbose_name='契约版本')),
                ('definition', models.JSONField(validators=[apps.skills.models.validate_chain_definition], verbose_name='链定义')),
                ('legacy_skill_ids', models.JSONField(blank=True, default=list, validators=[apps.skills.models.validate_legacy_skill_ids], verbose_name='旧 Skill ID 兼容信息')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('enabled', '启用'), ('disabled', '停用'), ('rolled_back', '已回滚')], db_index=True, default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_skill_chains', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_chains', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': 'Skill 链',
                'verbose_name_plural': 'Skill 链',
                'ordering': ('name', 'version'),
            },
        ),
        migrations.CreateModel(
            name='SkillChainConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('layer', models.CharField(choices=[('global', '全局默认'), ('project', '项目覆盖'), ('feature', '功能覆盖'), ('instant', '即时指定')], db_index=True, max_length=20, verbose_name='配置层级')),
                ('feature_key', models.CharField(blank=True, max_length=120, verbose_name='功能标识')),
                ('request_key', models.CharField(blank=True, max_length=120, verbose_name='即时请求标识')),
                ('version_lock', models.CharField(blank=True, max_length=30, verbose_name='锁定版本')),
                ('overrides', models.JSONField(blank=True, default=dict, validators=[apps.skills.models.validate_object], verbose_name='层级覆盖')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='是否生效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='skills.skillchain', verbose_name='Skill 链')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_skill_chain_configurations', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_chain_configurations', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': 'Skill 链配置',
                'verbose_name_plural': 'Skill 链配置',
                'ordering': ('layer', '-updated_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='skillchain',
            constraint=models.UniqueConstraint(fields=('project', 'name', 'version'), name='skills_chain_scope_name_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='skillchainconfiguration',
            constraint=models.UniqueConstraint(fields=('chain', 'layer', 'project', 'feature_key', 'request_key'), name='skills_chain_config_scope_uniq'),
        ),
    ]
