# Generated by Django 5.0.14 on 2026-09-20 03:57

import apps.skills.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0009_skillchain_skillchainconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillchainconfiguration',
            name='configuration_snapshot',
            field=models.JSONField(blank=True, default=dict, validators=[apps.skills.models.validate_object], verbose_name='配置快照'),
        ),
    ]
