# Generated by Django 5.0.14 on 2026-09-20 10:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0011_backfill_chain_configuration_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillChainGovernanceAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(db_index=True, verbose_name='对象编号')),
                ('action', models.CharField(db_index=True, max_length=30, verbose_name='操作')),
                ('before_state', models.JSONField(blank=True, default=dict, verbose_name='变更前快照')),
                ('after_state', models.JSONField(blank=True, default=dict, verbose_name='变更后快照')),
                ('reason', models.CharField(blank=True, max_length=500, verbose_name='操作说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_chain_governance_audits', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governance_audits', to='skills.skillchain', verbose_name='Skill 链')),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governance_audits', to='skills.skillchainconfiguration', verbose_name='Skill 链配置')),
            ],
            options={
                'verbose_name': 'Skill 链治理审计',
                'verbose_name_plural': 'Skill 链治理审计',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
