# Generated by Django 5.0.14 on 2026-09-24 05:43

import apps.skills.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('skills', '0013_skillchain_lifecycle_audit_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillChainRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, verbose_name='幂等键')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '运行中'), ('pause_requested', '请求暂停'), ('paused', '已暂停'), ('waiting_human', '等待人工'), ('completed', '已完成'), ('failed', '失败'), ('timed_out', '已超时'), ('cancel_requested', '请求取消'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=30, verbose_name='运行状态')),
                ('input_snapshot', models.JSONField(default=dict, validators=[apps.skills.models.validate_object], verbose_name='输入快照')),
                ('execution_snapshot', models.JSONField(default=dict, validators=[apps.skills.models.validate_object], verbose_name='执行快照')),
                ('output_snapshot', models.JSONField(blank=True, default=dict, validators=[apps.skills.models.validate_object], verbose_name='输出快照')),
                ('current_node_id', models.CharField(blank=True, max_length=80, verbose_name='当前节点')),
                ('checkpoint_node_id', models.CharField(blank=True, max_length=80, verbose_name='安全检查点')),
                ('control_request', models.CharField(blank=True, max_length=30, verbose_name='控制请求')),
                ('error_code', models.CharField(blank=True, max_length=60, verbose_name='错误编码')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('attempt', models.PositiveIntegerField(default=1, verbose_name='运行尝试次数')),
                ('task_id', models.CharField(blank=True, max_length=150, verbose_name='任务编号')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='skills.skillchain', verbose_name='蓝图')),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='skills.skillchainconfiguration', verbose_name='生效配置')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_chain_runs', to='projects.project', verbose_name='项目')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_skill_chain_runs', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
            ],
            options={
                'verbose_name': 'Skill 链运行',
                'verbose_name_plural': 'Skill 链运行',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SkillChainNodeRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(max_length=80, verbose_name='节点标识')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='节点顺序')),
                ('node_type', models.CharField(max_length=30, verbose_name='节点类型')),
                ('status', models.CharField(db_index=True, default='pending', max_length=30, verbose_name='节点状态')),
                ('definition_snapshot', models.JSONField(default=dict, validators=[apps.skills.models.validate_object], verbose_name='节点定义快照')),
                ('input_snapshot', models.JSONField(blank=True, default=dict, validators=[apps.skills.models.validate_object], verbose_name='节点输入快照')),
                ('output_snapshot', models.JSONField(blank=True, default=dict, validators=[apps.skills.models.validate_object], verbose_name='节点输出快照')),
                ('attempt', models.PositiveIntegerField(default=0, verbose_name='节点尝试次数')),
                ('max_retries', models.PositiveIntegerField(default=0, verbose_name='最大重试次数')),
                ('checkpoint_safe', models.BooleanField(default=False, verbose_name='是否安全检查点')),
                ('error_code', models.CharField(blank=True, max_length=60, verbose_name='错误编码')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='skills.skillchainrun', verbose_name='父运行')),
            ],
            options={
                'verbose_name': 'Skill 链节点运行',
                'verbose_name_plural': 'Skill 链节点运行',
                'ordering': ('position', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='SkillChainRunEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(verbose_name='序号')),
                ('event_type', models.CharField(max_length=40, verbose_name='事件类型')),
                ('from_status', models.CharField(blank=True, max_length=30, verbose_name='原状态')),
                ('to_status', models.CharField(blank=True, max_length=30, verbose_name='目标状态')),
                ('node_key', models.CharField(blank=True, max_length=80, verbose_name='节点标识')),
                ('payload', models.JSONField(blank=True, default=dict, validators=[apps.skills.models.validate_object], verbose_name='事件内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='skills.skillchainnoderun', verbose_name='节点')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='skills.skillchainrun', verbose_name='父运行')),
            ],
            options={
                'verbose_name': 'Skill 链运行事件',
                'verbose_name_plural': 'Skill 链运行事件',
                'ordering': ('sequence',),
            },
        ),
        migrations.AddConstraint(
            model_name='skillchainrun',
            constraint=models.UniqueConstraint(fields=('requested_by', 'idempotency_key'), name='skills_run_request_idempotency_uniq'),
        ),
        migrations.AddConstraint(
            model_name='skillchainnoderun',
            constraint=models.UniqueConstraint(fields=('run', 'node_id'), name='skills_node_run_unique_node'),
        ),
        migrations.AddConstraint(
            model_name='skillchainrunevent',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='skills_run_event_sequence_uniq'),
        ),
    ]
