# Generated by Django 5.0.14 on 2026-09-16 03:56

import apps.tests.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environments', '0002_environment_health_checked_at_and_more'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_id', models.CharField(max_length=50, unique=True, verbose_name='用例编号')),
                ('title', models.CharField(max_length=500, verbose_name='用例标题')),
                ('precondition', models.TextField(blank=True, verbose_name='前置条件')),
                ('steps', models.JSONField(default=list, validators=[apps.tests.models.validate_json_array], verbose_name='测试步骤')),
                ('input_data', models.JSONField(default=dict, validators=[apps.tests.models.validate_json_object], verbose_name='输入数据')),
                ('expected_result', models.TextField(verbose_name='预期结果')),
                ('priority', models.CharField(choices=[('P0', 'P0'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], default='P1', max_length=10, verbose_name='优先级')),
                ('case_type', models.CharField(choices=[('function', '功能'), ('boundary', '边界'), ('exception', '异常'), ('security', '安全'), ('api', '接口'), ('ai', 'AI'), ('ui', '界面'), ('app', '应用'), ('perf', '性能'), ('linkage', '业务链路')], default='function', max_length=50, verbose_name='用例类型')),
                ('is_automation', models.BooleanField(default=False, verbose_name='是否自动化')),
                ('automation_difficulty', models.CharField(blank=True, choices=[('low', '低'), ('medium', '中'), ('high', '高')], max_length=10, verbose_name='自动化难度')),
                ('automation_tech', models.CharField(blank=True, choices=[('pytest', 'pytest'), ('playwright', 'Playwright'), ('appium', 'Appium'), ('locust', 'Locust'), ('jmeter', 'JMeter')], max_length=50, verbose_name='自动化技术')),
                ('requirement_mapping', models.JSONField(default=dict, validators=[apps.tests.models.validate_json_object], verbose_name='需求映射')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'ordering': ('project__name', 'case_id'),
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='执行名称')),
                ('mode', models.CharField(choices=[('immediate', '立即执行'), ('script', '脚本执行'), ('full', '全量执行')], default='immediate', max_length=20, verbose_name='执行模式')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='执行状态')),
                ('execution_config', models.JSONField(default=dict, validators=[apps.tests.models.validate_json_object], verbose_name='执行配置')),
                ('summary', models.JSONField(default=dict, validators=[apps.tests.models.validate_json_object], verbose_name='执行摘要')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_test_runs', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_runs', to='environments.environment', verbose_name='执行环境')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='projects.project', verbose_name='项目')),
                ('test_cases', models.ManyToManyField(blank=True, related_name='test_runs', to='tests.testcase', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': '测试执行',
                'verbose_name_plural': '测试执行',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('passed', '通过'), ('failed', '失败'), ('skipped', '跳过'), ('error', '错误')], default='pending', max_length=20, verbose_name='结果状态')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='耗时毫秒')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(599)], verbose_name='响应状态码')),
                ('response_summary', models.JSONField(default=dict, validators=[apps.tests.models.validate_json_object], verbose_name='响应摘要')),
                ('assertions', models.JSONField(default=list, validators=[apps.tests.models.validate_json_array], verbose_name='断言结果')),
                ('error_code', models.CharField(blank=True, max_length=80, verbose_name='错误编码')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tests.testcase', verbose_name='测试用例')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tests.testrun', verbose_name='测试执行')),
            ],
            options={
                'verbose_name': '测试结果',
                'verbose_name_plural': '测试结果',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evaluator', models.CharField(choices=[('rule', '规则'), ('llm', '模型'), ('manual', '人工')], default='rule', max_length=20, verbose_name='评价来源')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='评分')),
                ('grade', models.CharField(blank=True, max_length=20, verbose_name='等级')),
                ('dimensions', models.JSONField(default=dict, validators=[apps.tests.models.validate_json_object], verbose_name='评价维度')),
                ('recommendations', models.JSONField(default=list, validators=[apps.tests.models.validate_json_array], verbose_name='改进建议')),
                ('summary', models.TextField(blank=True, verbose_name='评价摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='tests.testresult', verbose_name='测试结果')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='tests.testrun', verbose_name='测试执行')),
            ],
            options={
                'verbose_name': '测试评价',
                'verbose_name_plural': '测试评价',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['project', 'case_type', 'priority'], name='tests_tc_project_type_prio_idx'),
        ),
        migrations.AddIndex(
            model_name='testrun',
            index=models.Index(fields=['project', 'status', 'created_at'], name='tests_run_project_status_idx'),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['run', 'status'], name='tests_result_run_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='testresult',
            constraint=models.UniqueConstraint(fields=('run', 'test_case'), name='tests_result_run_case_uniq'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['run', 'evaluator'], name='tests_eval_run_evaluator_idx'),
        ),
    ]
