# Generated by Django 5.0.14 on 2026-09-04 06:41

import apps.configs.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0002_modelusagerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('scope', models.CharField(choices=[('global', '全局默认'), ('project', '项目级'), ('scene', '场景级'), ('instant', '即时指定')], db_index=True, max_length=20, verbose_name='作用域')),
                ('scene_type', models.CharField(choices=[('default', '全局默认'), ('requirement_analysis', '需求分析'), ('case_gen', '用例生成'), ('case_review', '用例评审'), ('api_test', '接口测试'), ('ai_test', 'AI 测试'), ('ui_test', 'UI 测试'), ('app_test', 'APP 测试'), ('perf_test', '性能测试'), ('screenshot_analysis', '截图识别'), ('report_gen', '报告生成')], db_index=True, default='default', max_length=50, verbose_name='场景类型')),
                ('content', models.TextField(verbose_name='提示词内容')),
                ('variables', models.JSONField(blank=True, default=dict, validators=[apps.configs.models.validate_variables_object], verbose_name='模板变量')),
                ('version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='版本')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '提示词配置',
                'verbose_name_plural': '提示词配置',
                'ordering': ('scope', 'scene_type', 'name', '-version'),
                'indexes': [models.Index(fields=['scope', 'scene_type', 'is_active'], name='config_prompt_lookup_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='promptconfig',
            constraint=models.UniqueConstraint(fields=('name', 'scope', 'scene_type', 'version'), name='config_prompt_version_uniq'),
        ),
    ]
