# Generated by Django 5.0.14 on 2026-09-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0004_seed_default_prompts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelconfig',
            name='model_name',
            field=models.CharField(max_length=200, verbose_name='模型名称'),
        ),
        migrations.AlterField(
            model_name='modelconfig',
            name='model_type',
            field=models.CharField(choices=[('chat', '对话'), ('embedding', '向量'), ('vision', '视觉'), ('multimodal', '全模态'), ('image_generation', '图像生成与编辑'), ('video', '视频生成'), ('audio', '音频理解与生成'), ('tts', '语音合成'), ('asr', '语音识别'), ('realtime', '实时交互'), ('rerank', '重排序'), ('three_d', '三维生成'), ('other', '其他 / 待确认能力')], db_index=True, default='chat', max_length=20, verbose_name='模型类型'),
        ),
    ]
