# Generated by Django 5.0.14 on 2026-09-07 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0005_alter_modelconfig_model_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRoutingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(choices=[('global', '平台全局默认'), ('requirement_analysis', '需求深度分析'), ('screenshot_analysis', '截图与视觉分析'), ('case_generation', '测试用例生成'), ('case_review', '测试用例评审'), ('agent_execution', '智能体执行'), ('report_generation', '报告生成'), ('knowledge_model', '知识库模型任务')], db_index=True, max_length=64, unique=True, verbose_name='功能标识')),
                ('allow_fallback', models.BooleanField(default=False, verbose_name='允许备用切换')),
                ('allow_deterministic_baseline', models.BooleanField(default=False, verbose_name='允许确定性基线')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('backup_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_route_policies', to='configs.modelconfig', verbose_name='备用模型')),
                ('primary_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_route_policies', to='configs.modelconfig', verbose_name='主模型')),
            ],
            options={
                'verbose_name': '模型路由策略',
                'verbose_name_plural': '模型路由策略',
                'ordering': ('feature_key',),
                'indexes': [models.Index(fields=['feature_key', 'is_active'], name='config_route_policy_idx')],
            },
        ),
    ]
