# Generated by Django 5.0.14 on 2026-09-14

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configs", "0006_modelroutingpolicy"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelCallRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("feature_key", models.CharField(db_index=True, max_length=64)),
                ("task_type", models.CharField(blank=True, default="", max_length=64)),
                ("stage", models.CharField(default="model_call", max_length=64)),
                (
                    "provider",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "model_type",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "route_source",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("is_fallback", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "failure_stage",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("error_code", models.CharField(blank=True, default="", max_length=80)),
                ("retryable", models.BooleanField(default=False)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "cost_status",
                    models.CharField(
                        choices=[
                            ("not_reported", "Not reported"),
                            ("estimated", "Estimated"),
                            ("reported", "Reported"),
                        ],
                        default="not_reported",
                        max_length=20,
                    ),
                ),
                ("cost_hint", models.CharField(blank=True, default="", max_length=160)),
                ("trace", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "model_config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_records",
                        to="configs.modelconfig",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-pk"),
                "indexes": [
                    models.Index(
                        fields=["feature_key", "created_at"],
                        name="config_call_feature_time_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="config_call_status_time_idx",
                    ),
                ],
            },
        ),
    ]
