# Generated by Django 5.0.14 on 2026-09-05 15:46

import apps.requirement_analysis.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='版本')),
                ('source_type', models.CharField(choices=[('file', '文件'), ('online_link', '在线链接'), ('screenshot', '截图'), ('manual', '手工录入')], default='manual', max_length=20, verbose_name='来源类型')),
                ('source_url', models.URLField(blank=True, max_length=1000, verbose_name='来源地址')),
                ('file_path', models.CharField(blank=True, max_length=1000, verbose_name='文件路径')),
                ('content_text', models.TextField(blank=True, verbose_name='正文')),
                ('status', models.CharField(choices=[('uploaded', '已上传'), ('parsing', '解析中'), ('analyzing', '分析中'), ('analyzed', '已分析'), ('failed', '失败')], db_index=True, default='uploaded', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_requirement_documents', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_documents', to='projects.project', verbose_name='项目')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modules', models.JSONField(default=list, validators=[apps.requirement_analysis.models.validate_list], verbose_name='功能模块')),
                ('functions', models.JSONField(default=list, validators=[apps.requirement_analysis.models.validate_list], verbose_name='功能点')),
                ('linkages', models.JSONField(default=list, validators=[apps.requirement_analysis.models.validate_list], verbose_name='联合功能')),
                ('test_points', models.JSONField(default=list, validators=[apps.requirement_analysis.models.validate_list], verbose_name='测试点')),
                ('coverage_report', models.JSONField(default=dict, validators=[apps.requirement_analysis.models.validate_object], verbose_name='覆盖度报告')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='requirement_analysis.requirementdocument', verbose_name='需求文档')),
            ],
            options={
                'verbose_name': '需求分析结果',
                'verbose_name_plural': '需求分析结果',
                'ordering': ('-created_at',),
            },
        ),
    ]
