# Generated by Django 5.0.14 on 2026-09-06 08:44

import apps.requirement_analysis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementdocument',
            name='parse_confidence',
            field=models.FloatField(default=0.0, verbose_name='解析置信度'),
        ),
        migrations.AddField(
            model_name='requirementdocument',
            name='parse_evidence',
            field=models.JSONField(default=list, validators=[apps.requirement_analysis.models.validate_list], verbose_name='解析证据'),
        ),
        migrations.AddField(
            model_name='requirementdocument',
            name='parse_warnings',
            field=models.JSONField(default=list, validators=[apps.requirement_analysis.models.validate_list], verbose_name='解析警告'),
        ),
    ]
