# Generated by Django 5.0.14 on 2026-09-06 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0002_requirementdocument_parse_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementdocument',
            name='parse_confidence',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='解析置信度'),
        ),
    ]
