# Generated by Django 5.0.14 on 2026-09-10

import apps.requirement_analysis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requirement_analysis", "0003_alter_requirementdocument_parse_confidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirementdocument",
            name="visual_analysis_report",
            field=models.JSONField(
                default=dict,
                validators=[apps.requirement_analysis.models.validate_object],
                verbose_name="视觉分析报告",
            ),
        ),
    ]
