# Generated by Django 5.0.14 on 2026-09-10

import apps.requirement_analysis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requirement_analysis", "0004_requirementdocument_visual_analysis_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirementdocument",
            name="analysis_baseline",
            field=models.JSONField(
                default=dict,
                validators=[apps.requirement_analysis.models.validate_object],
                verbose_name="分析稳定性基线",
            ),
        ),
        migrations.AddField(
            model_name="requirementanalysis",
            name="analysis_fingerprint",
            field=models.CharField(
                db_index=True,
                default="",
                blank=True,
                max_length=64,
                verbose_name="分析指纹",
            ),
        ),
        migrations.AddField(
            model_name="requirementanalysis",
            name="quality_status",
            field=models.CharField(
                choices=[
                    ("complete", "完整"),
                    ("partial", "部分完成"),
                    ("needs_review", "待复核"),
                    ("failed", "失败"),
                ],
                db_index=True,
                default="needs_review",
                max_length=20,
                verbose_name="完整性状态",
            ),
        ),
        migrations.AddField(
            model_name="requirementanalysis",
            name="source_fingerprint",
            field=models.CharField(
                db_index=True,
                default="",
                blank=True,
                max_length=64,
                verbose_name="源指纹",
            ),
        ),
    ]
