# Generated by Django 5.0.14 on 2026-09-16

import apps.business_linkage.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessLinkage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="链路名称")),
                (
                    "steps",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[apps.business_linkage.models.validate_json_array],
                        verbose_name="链路步骤",
                    ),
                ),
                (
                    "dependencies",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[apps.business_linkage.models.validate_json_array],
                        verbose_name="依赖关系",
                    ),
                ),
                (
                    "test_case_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[apps.business_linkage.models.validate_identifier_array],
                        verbose_name="关联用例",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_linkages",
                        to="projects.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "业务链路",
                "verbose_name_plural": "业务链路",
                "ordering": ("project__name", "name", "-created_at"),
            },
        ),
        migrations.AddIndex(
            model_name="businesslinkage",
            index=models.Index(
                fields=["project", "name"],
                name="biz_linkage_proj_name_idx",
            ),
        ),
    ]
