<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import WorkspaceShell from '../components/workspace/WorkspaceShell.vue'
import * as api from '../api/knowledge'
import { listProjects } from '../api/projects'

const bases = ref([]); const projects = ref([]); const selectedId = ref(''); const documents = ref([]); const qa = ref([])
const loading = ref(true); const error = ref(''); const notice = ref(''); const modal = ref(''); const busy = ref(false)
const file = ref(null); const fileInput = ref(null); const searchText = ref(''); const results = ref([]); const formError = ref('')
const baseForm = reactive({ name: '', description: '', category: 'project', project: '' }); const qaForm = reactive({ question: '', answer: '' }); const review = reactive({ decision: 'approved', note: '' })
const selected = computed(() => bases.value.find(item => item.id === selectedId.value))

function explain(err, fallback) { if (err.response?.status === 401) return '登录已过期，请重新登录。'; if (err.response?.status === 403) return '当前账号没有执行此操作的权限。'; const data = err.response?.data; if (typeof data?.detail === 'string') return data.detail; const first = data && Object.values(data)[0]; return Array.isArray(first) ? first.join('；') : (first || fallback) }
async function load() { loading.value = true; error.value = ''; try { [bases.value, projects.value] = await Promise.all([api.listKnowledgeBases(), listProjects()]); if (!bases.value.some(item => item.id === selectedId.value)) selectedId.value = bases.value[0]?.id || ''; await loadAssets() } catch (err) { error.value = explain(err, '知识库加载失败，请重试。') } finally { loading.value = false } }
async function loadAssets() { if (!selectedId.value) { documents.value = []; qa.value = []; return } try { [documents.value, qa.value] = await Promise.all([api.listDocuments(selectedId.value), api.listQA(selectedId.value)]) } catch (err) { error.value = explain(err, '知识库内容加载失败，请重试。') } }
function openBase(item = null) { Object.assign(baseForm, { name: item?.name || '', description: item?.description || '', category: item?.category || 'project', project: item?.project || projects.value[0]?.id || '' }); modal.value = 'base'; formError.value = '' }
async function saveBase() { formError.value = ''; if (!baseForm.name.trim()) { formError.value = '请输入知识库名称。'; return } busy.value = true; try { const payload = { ...baseForm, project: baseForm.project || null }; if (selected.value) await api.updateKnowledgeBase(selected.value.id, payload); else await api.createKnowledgeBase(payload); modal.value = ''; ElMessage.success('知识库已保存'); await load() } catch (err) { formError.value = explain(err, '保存失败，请重试。') } finally { busy.value = false } }
function onFile(event) { file.value = event.target.files?.[0] || null }
function chooseFile() { fileInput.value?.click() }
async function upload() { if (!file.value || !selectedId.value) return; busy.value = true; const data = new FormData(); data.append('knowledge_base', selectedId.value); data.append('title', file.value.name.replace(/\.[^.]+$/, '')); data.append('file', file.value); try { await api.uploadDocument(data); notice.value = '文档已上传，请继续解析并向量化。'; file.value = null; await loadAssets() } catch (err) { notice.value = explain(err, '上传失败，请检查文件后重试。') } finally { busy.value = false } }
async function action(fn, success) { busy.value = true; notice.value = ''; try { await fn(); notice.value = success; ElMessage.success(success); await loadAssets() } catch (err) { notice.value = explain(err, '操作失败，请重试。'); ElMessage.error(notice.value) } finally { busy.value = false } }
function reviewDocument(doc) { review.decision = doc.review_status === 'approved' ? 'paused' : 'approved'; review.note = ''; modal.value = `review:${doc.id}`; formError.value = '' }
async function submitReview(doc) { await action(() => api.reviewDocument(doc.id, review), '文档审核状态已更新'); modal.value = '' }
async function runSearch() { if (!searchText.value.trim()) { notice.value = '请先输入要检索的问题或关键词。'; return } busy.value = true; try { results.value = (await api.searchKnowledge({ query: searchText.value, knowledge_base_ids: [selectedId.value], top_k: 10 })).results || [] } catch (err) { ElMessage.error(explain(err, '检索失败，请重试。')) } finally { busy.value = false } }
function openQA() { Object.assign(qaForm, { question: '', answer: '' }); modal.value = 'qa'; formError.value = '' }
async function saveQA() { if (!qaForm.question.trim() || !qaForm.answer.trim()) { formError.value = '问题和答案都不能为空。'; return } await action(() => api.createQA({ ...qaForm, knowledge_base: selectedId.value }), '问答已添加'); modal.value = '' }
async function reviewQA(item) { const decision = item.review_status === 'approved' ? 'paused' : 'approved'; await action(() => api.reviewQA(item.id, { decision, note: '' }), '问答审核状态已更新') }
onMounted(load)
</script>

<template>
  <WorkspaceShell active="knowledge"><div class="workspace-content model-page knowledge-page">
    <div class="page-title-row"><div><p class="workspace-eyebrow">KNOWLEDGE CENTER</p><h1>知识库</h1><p class="workspace-lead">管理文档与问答内容，让已审核的知识可被智能体检索。</p></div><button class="primary-action" @click="openBase()">＋ 新建知识库</button></div>
    <div v-if="notice" class="knowledge-notice" role="status">{{ notice }}</div><div v-if="error" class="knowledge-error" role="alert">{{ error }} <button class="text-action" @click="load">重新加载</button></div><div v-if="!loading && !selected" class="knowledge-notice">当前还没有知识库。点击右上角“新建知识库”，创建后即可使用文档上传、解析、向量化、问答和审核功能。</div>
    <section v-if="!loading" class="knowledge-layout"><aside class="knowledge-panel"><div class="knowledge-heading"><h2>知识库</h2><button class="text-action" @click="load">刷新</button></div><div v-if="!bases.length" class="knowledge-empty">暂无可访问知识库</div><div class="knowledge-list"><button v-for="item in bases" :key="item.id" :class="{ active: item.id === selectedId }" @click="selectedId = item.id; loadAssets()"><b>{{ item.name }}</b><small>{{ item.category_label }} · {{ item.status_label }}</small></button></div><button v-if="selected" class="text-action" @click="openBase(selected)">编辑当前知识库</button></aside>
      <main class="knowledge-panel"><div v-if="!selected" class="knowledge-empty">请先创建或选择知识库。</div><template v-else><div class="knowledge-heading"><div><h2>{{ selected.name }}</h2><small>{{ selected.description || '暂无说明' }}</small></div><div class="knowledge-actions"><div><input class="knowledge-file-input" type="file" accept=".txt,.md,.markdown,.pdf,.docx" @change="onFile"><small v-if="file" class="knowledge-file-name">已选择：{{ file.name }}</small></div><button class="primary-action" :disabled="busy || !file || !selectedId" @click="upload">{{ busy ? '处理中…' : (!file ? '先选择文档' : '上传文档') }}</button><button class="secondary-action" @click="openQA">＋ 添加问答</button></div></div>
        <div class="knowledge-search"><input v-model="searchText" placeholder="检索已审核知识…" @keyup.enter="runSearch"><button class="primary-action" :disabled="busy" @click="runSearch">检索</button></div><div v-if="results.length" class="knowledge-results"><article v-for="item in results" :key="item.id" class="knowledge-result"><b>{{ item.title || item.question || '检索结果' }}</b><p>{{ item.text || item.answer || item.content }}</p><small>相关度 {{ Number(item.score || 0).toFixed(3) }}</small></article></div>
        <h3>文档（{{ documents.length }}）</h3><div v-if="!documents.length" class="knowledge-empty">还没有文档，上传 TXT、Markdown、PDF 或 DOCX 开始。</div><table v-else class="knowledge-table"><thead><tr><th>文档</th><th>解析状态</th><th>审核</th><th>操作</th></tr></thead><tbody><tr v-for="doc in documents" :key="doc.id"><td><b>{{ doc.title }}</b><br><small>{{ doc.source_type_label }}</small></td><td><span class="knowledge-chip">{{ doc.status_label }}</span></td><td>{{ doc.review_status_label }}</td><td class="knowledge-actions"><button class="text-action" @click="action(() => api.parseDocument(doc.id), '文档解析完成')">解析</button><button class="text-action" @click="action(() => api.indexDocument(doc.id), '文档向量化完成')">向量化</button><button class="text-action" @click="reviewDocument(doc)">审核</button></td></tr></tbody></table>
        <h3>问答（{{ qa.length }}）</h3><div v-if="!qa.length" class="knowledge-empty">暂无问答内容。</div><table v-else class="knowledge-table"><tbody><tr v-for="item in qa" :key="item.id"><td><b>Q：{{ item.question }}</b><br>A：{{ item.answer }}</td><td>{{ item.review_status_label }}</td><td><button class="text-action" @click="reviewQA(item)">{{ item.review_status === 'approved' ? '暂缓' : '通过' }}</button></td></tr></tbody></table>
      </template></main></section>
    <div v-else class="state-panel" role="status"><span class="loading-ring"></span><b>正在加载知识库</b></div>
  </div><Teleport to="body"><div v-if="modal" class="modal-backdrop" @click.self="modal = ''"><section class="config-modal knowledge-modal"><header><h2>{{ modal === 'qa' ? '添加问答' : modal.startsWith('review:') ? '审核文档' : (selected ? '编辑知识库' : '新建知识库') }}</h2><button @click="modal = ''">×</button></header><form @submit.prevent="modal === 'qa' ? saveQA() : modal.startsWith('review:') ? submitReview(documents.find(item => item.id === modal.slice(7))) : saveBase()"><fieldset class="knowledge-form" :disabled="busy"><template v-if="modal === 'qa'"><label>问题<textarea v-model="qaForm.question" rows="3"></textarea></label><label>答案<textarea v-model="qaForm.answer" rows="5"></textarea></label></template><template v-else-if="modal.startsWith('review:')"><label>审核决定<select v-model="review.decision"><option value="approved">通过</option><option value="rejected">拒绝</option><option value="paused">暂缓</option></select></label><label>审核备注<textarea v-model="review.note" rows="3"></textarea></label></template><template v-else><label>名称<input v-model="baseForm.name" required></label><label>说明<textarea v-model="baseForm.description" rows="3"></textarea></label><label>分类<select v-model="baseForm.category"><option value="project">项目知识</option><option value="builtin">内置知识</option><option value="faq">常见问答</option><option value="policy">规范制度</option></select></label></template><p v-if="formError" class="knowledge-error" role="alert">{{ formError }}</p></fieldset><footer><button type="button" class="secondary-action" @click="modal = ''">取消</button><button type="submit" class="primary-action" :disabled="busy">{{ busy ? '处理中…' : '保存' }}</button></footer></form></section></div></Teleport></WorkspaceShell>
</template>
