<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import WorkspaceShell from '../components/workspace/WorkspaceShell.vue'
import { listProjects } from '../api/projects'
import { analyzeRequirementDocument, createRequirementDocument, deleteRequirementDocument, identifyRequirementLinkages, listRequirementDocuments, parseRequirementDocument } from '../api/requirements'

const projects = ref([]); const documents = ref([]); const selectedProject = ref(''); const selectedDocument = ref(null)
const loading = ref(true); const busy = ref(false); const error = ref(''); const notice = ref(''); const formError = ref(''); const showForm = ref(false)
const file = ref(null); const form = reactive({ title: '', version: '1.0', source_type: 'manual', source_url: '', content_text: '' })
const canWrite = computed(() => ['admin', 'platform_admin', 'owner', 'manager'].includes(selectedProject.value ? projects.value.find(item => item.id === selectedProject.value)?.current_role : ''))

function explain(err, fallback) { const data = err.response?.data; if (typeof data?.detail === 'string') return data.detail; const first = data && Object.values(data)[0]; return Array.isArray(first) ? first[0] : (typeof first === 'string' ? first : fallback) }
async function loadProjects() { try { projects.value = await listProjects(); if (!selectedProject.value && projects.value.length) selectedProject.value = projects.value[0].id } catch (err) { error.value = explain(err, '项目加载失败，请确认服务状态后重试。') } }
async function loadDocuments() { if (!selectedProject.value) { documents.value = []; selectedDocument.value = null; loading.value = false; return }; loading.value = true; error.value = ''; try { documents.value = await listRequirementDocuments(selectedProject.value); selectedDocument.value = documents.value.find(item => item.id === selectedDocument.value?.id) || documents.value[0] || null } catch (err) { error.value = explain(err, '需求文档加载失败，请重试。') } finally { loading.value = false } }
async function refresh() { await loadProjects(); await loadDocuments() }
function openCreate() { Object.assign(form, { title: '', version: '1.0', source_type: 'manual', source_url: '', content_text: '' }); file.value = null; formError.value = ''; showForm.value = true }
function onFile(event) { file.value = event.target.files?.[0] || null }
async function saveDocument() { formError.value = ''; if (!selectedProject.value || !form.title.trim()) { formError.value = '请选择项目并填写文档标题。'; return }; if (form.source_type === 'manual' && !form.content_text.trim()) { formError.value = '手工录入内容不能为空。'; return }; if (['file', 'screenshot'].includes(form.source_type) && !file.value) { formError.value = '请选择需求文件。'; return }; if (form.source_type === 'online_link' && !form.source_url.trim()) { formError.value = '在线来源必须填写链接。'; return }; busy.value = true; try { const payload = new FormData(); payload.append('project', selectedProject.value); payload.append('title', form.title); payload.append('version', form.version); payload.append('source_type', form.source_type); if (form.source_url) payload.append('source_url', form.source_url); if (form.content_text) payload.append('content_text', form.content_text); if (file.value) payload.append('file', file.value); const created = await createRequirementDocument(payload); showForm.value = false; notice.value = '需求文档已创建，请继续解析和分析。'; await loadDocuments(); selectedDocument.value = created } catch (err) { formError.value = explain(err, '保存失败，请检查文档内容后重试。') } finally { busy.value = false } }
async function action(fn, success) { if (!selectedDocument.value) return; busy.value = true; error.value = ''; try { const result = await fn(selectedDocument.value.id); notice.value = fn === identifyRequirementLinkages && !result?.linkages?.length ? '联合识别已完成，当前需求未发现跨模块联动场景。' : success; await loadDocuments(); selectedDocument.value = documents.value.find(item => item.id === selectedDocument.value?.id) || result } catch (err) { error.value = explain(err, '操作失败，请重试。') } finally { busy.value = false } }
async function removeDocument() { if (!selectedDocument.value || !window.confirm('确定删除当前需求文档吗？')) return; busy.value = true; try { await deleteRequirementDocument(selectedDocument.value.id); selectedDocument.value = null; notice.value = '需求文档已删除。'; await loadDocuments() } catch (err) { error.value = explain(err, '删除失败，请重试。') } finally { busy.value = false } }
onMounted(refresh)
</script>

<template>
  <WorkspaceShell active="requirements"><div class="workspace-content requirement-page">
    <div class="page-title-row"><div><p class="workspace-eyebrow">REQUIREMENT INTELLIGENCE</p><h1>需求智能分析</h1><p class="workspace-lead">导入需求文档，逐步完成解析、功能拆解、联合识别和测试点确认。</p></div><button class="primary-action" :disabled="!canWrite" @click="openCreate">＋ 导入需求</button></div>
    <div v-if="notice" class="requirement-notice" role="status">{{ notice }}</div><div v-if="error" class="requirement-error" role="alert">{{ error }} <button class="text-action" @click="refresh">重新加载</button></div>
    <div class="requirement-toolbar"><label>项目<select v-model="selectedProject" @change="loadDocuments"><option v-for="item in projects" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><button class="secondary-action" @click="refresh">刷新</button></div>
    <section v-if="loading" class="state-panel"><span class="loading-ring"></span><b>正在加载需求文档</b></section>
    <section v-else class="requirement-layout"><aside class="requirement-panel"><div class="requirement-heading"><h2>需求文档</h2><span>{{ documents.length }}</span></div><div v-if="!documents.length" class="requirement-empty">暂无需求文档，请从右上角导入。</div><button v-for="item in documents" :key="item.id" class="requirement-document" :class="{ active: item.id === selectedDocument?.id }" @click="selectedDocument = item"><b>{{ item.title }}</b><small>v{{ item.version }} · {{ item.status_label }}</small></button></aside>
      <main class="requirement-panel"><div v-if="!selectedDocument" class="requirement-empty">选择需求文档后开始分析。</div><template v-else><div class="requirement-heading"><div><h2>{{ selectedDocument.title }}</h2><small>{{ selectedDocument.source_type_label }} · {{ selectedDocument.status_label }}</small></div><button class="danger-action" :disabled="busy || !canWrite" @click="removeDocument">删除</button></div><div v-if="selectedDocument.parse_warnings?.length" class="requirement-error" role="alert"><b>来源解析需要处理：</b><span v-for="warning in selectedDocument.parse_warnings" :key="warning">{{ warning }}</span></div><div v-if="selectedDocument.parse_confidence !== undefined" class="requirement-source-meta">来源证据 {{ selectedDocument.parse_evidence?.length || 0 }} 条 · 解析置信度 {{ Math.round((selectedDocument.parse_confidence || 0) * 100) }}%<span v-if="selectedDocument.parse_confidence < 0.75"> · 待人工确认</span></div><div class="requirement-actions"><button class="secondary-action" :disabled="busy || !canWrite" @click="action(parseRequirementDocument, '文档解析完成')">解析</button><button class="primary-action" :disabled="busy || !canWrite" @click="action(analyzeRequirementDocument, '需求深度分析完成')">深度分析</button><button class="secondary-action" :disabled="busy || !canWrite || !selectedDocument.latest_analysis" @click="action(identifyRequirementLinkages, '联合功能识别完成')">联合识别</button></div><div v-if="selectedDocument.latest_analysis" class="analysis-grid"><article><h3>功能模块（{{ selectedDocument.latest_analysis.modules.length }}）</h3><ul><li v-for="item in selectedDocument.latest_analysis.modules" :key="item.id">{{ item.name }}<small v-if="item.needs_confirmation"> · 待确认</small></li></ul></article><article><h3>功能点（{{ selectedDocument.latest_analysis.functions.length }}）</h3><ul><li v-for="item in selectedDocument.latest_analysis.functions" :key="item.id">{{ item.name }}<small v-if="item.needs_confirmation"> · 待确认</small></li></ul></article><article><h3>联合场景（{{ selectedDocument.latest_analysis.linkages.length }}）</h3><div v-if="selectedDocument.latest_analysis.linkages.length"><ul><li v-for="item in selectedDocument.latest_analysis.linkages" :key="item.id">{{ item.description || item.relationship }}</li></ul></div><p v-else class="requirement-empty requirement-empty--compact">当前需求未发现跨模块联动。请补充两个以上模块及明确的依赖、状态或数据关系后重试。</p></article><article><h3>测试点（{{ selectedDocument.latest_analysis.test_points.length }}）</h3><p v-if="selectedDocument.latest_analysis.coverage_report.needs_confirmation" class="requirement-error">当前结果仅是证据基线，需确认来源内容后再生成用例。</p><ul><li v-for="(item, index) in selectedDocument.latest_analysis.test_points" :key="index">{{ item.description || item.type }}<small v-if="item.needs_confirmation"> · 待确认</small></li></ul></article></div><div v-else class="requirement-empty">尚未生成分析结果，请先解析后执行深度分析。</div></template></main></section>
    <div v-if="showForm" class="modal-backdrop" @click.self="!busy && (showForm = false)"><section class="config-modal requirement-modal"><header><h2>导入需求文档</h2><button @click="showForm = false">×</button></header><div class="config-form"><label>标题<input v-model="form.title" maxlength="500"></label><label>版本<input v-model="form.version" maxlength="20"></label><label>来源<select v-model="form.source_type"><option value="manual">手工录入</option><option value="file">文档文件</option><option value="screenshot">截图 OCR</option><option value="online_link">在线链接</option></select></label><label v-if="form.source_type === 'online_link'">链接<input v-model="form.source_url" placeholder="https://..."></label><label v-if="form.source_type === 'manual'">正文<textarea v-model="form.content_text" rows="8"></textarea></label><label v-if="['file', 'screenshot'].includes(form.source_type)">文件<input type="file" accept=".txt,.md,.markdown,.pdf,.docx,.xlsx,.json,.png,.jpg,.jpeg,.webp" @change="onFile"></label><p v-if="formError" class="form-error" role="alert">{{ formError }}</p></div><footer><button class="secondary-action" @click="showForm = false">取消</button><button class="primary-action" :disabled="busy" @click="saveDocument">{{ busy ? '保存中…' : '创建文档' }}</button></footer></section></div>
  </div></WorkspaceShell>
</template>
